/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#0f131f',
        'on-surface': '#dfe2f3',
        'on-tertiary-container': '#461f00',
        primary: '#c4c0ff',
        'surface-container-low': '#171b28',
        'secondary-container': '#bb9300',
        'secondary-fixed-dim': '#eec13c',
        'primary-fixed': '#e3dfff',
        'on-primary-fixed-variant': '#3622ca',
        'on-error-container': '#ffdad6',
        'surface-container-high': '#262a37',
        'surface-container': '#1b1f2c',
        'primary-fixed-dim': '#c4c0ff',
        'on-secondary-fixed-variant': '#584400',
        secondary: '#eec13c',
        'on-tertiary-fixed-variant': '#713700',
        'on-secondary-fixed': '#241a00',
        'on-secondary-container': '#3e2f00',
        'surface-container-lowest': '#0a0e1a',
        'error-container': '#93000a',
        'primary-container': '#8781ff',
        'on-secondary': '#3d2e00',
        'tertiary-container': '#db761f',
        'on-primary': '#2000a4',
        'inverse-surface': '#dfe2f3',
        'tertiary-fixed-dim': '#ffb785',
        tertiary: '#ffb785',
        'surface-variant': '#313442',
        surface: '#0f131f',
        'tertiary-fixed': '#ffdcc6',
        'on-surface-variant': '#c7c4d8',
        'inverse-on-surface': '#2c303d',
        background: '#0f131f',
        'surface-container-highest': '#313442',
        'on-primary-fixed': '#100069',
        'secondary-fixed': '#ffe08f',
        outline: '#918fa1',
        'on-tertiary': '#502500',
        'inverse-primary': '#4f44e2',
        error: '#ffb4ab',
        'surface-bright': '#353946',
        'on-error': '#690005',
        'outline-variant': '#464555',
        'on-tertiary-fixed': '#301400',
        'on-primary-container': '#1b0091',
        'on-background': '#dfe2f3',
        'surface-tint': '#c4c0ff',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        base: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        xxl: '64px',
        gutter: '24px',
        'container-max': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['DM Sans', 'sans-serif'],
        display: ['Syne', 'sans-serif'],
        'label-md': ['DM Sans', 'sans-serif'],
        'headline-md': ['Syne', 'sans-serif'],
        'body-lg': ['DM Sans', 'sans-serif'],
        'display-lg-mobile': ['Syne', 'sans-serif'],
        'body-md': ['DM Sans', 'sans-serif'],
        'headline-sm': ['Syne', 'sans-serif'],
        'display-lg': ['Syne', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
      keyframes: {
        'subtle-pulse': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(108, 99, 255, 0.2)' },
          '50%': { boxShadow: '0 0 35px rgba(108, 99, 255, 0.4)' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%) rotate(45deg)' },
          '100%': { transform: 'translateX(100%) rotate(45deg)' },
        },
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
      },
      animation: {
        'pulse-glow': 'subtle-pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        shimmer: 'shimmer 3s infinite',
        'fade-in': 'fade-in 0.5s ease-out forwards',
        'slide-up': 'slide-up 0.4s ease-out forwards',
        float: 'float 3s ease-in-out infinite',
        'spin-slow': 'spin 60s linear infinite',
        'spin-slow-reverse': 'spin 45s linear infinite reverse',
      },
      backgroundImage: {
        mesh: `radial-gradient(at 0% 0%, rgba(108, 99, 255, 0.15) 0px, transparent 50%),
               radial-gradient(at 100% 100%, rgba(108, 99, 255, 0.1) 0px, transparent 50%),
               radial-gradient(at 50% 50%, rgba(15, 19, 31, 1) 0px, transparent 100%)`,
      },
    },
  },
  plugins: [],
}
