'use client';

import { AppShell } from '@/components/layout/AppShell';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { motion } from 'framer-motion';
import { useState } from 'react';
import { ChevronLeft, ChevronRight, Plus, Clock, RefreshCw, Loader2 } from 'lucide-react';
import { addDays, startOfWeek, format } from 'date-fns';
import toast from 'react-hot-toast';

const HOURS = Array.from({ length: 14 }, (_, i) => i + 7); // 7am - 8pm

export default function WeeklyPlannerPage() {
  const qc = useQueryClient();
  const [currentDate, setCurrentDate] = useState(new Date());
  const [regenerating, setRegenerating] = useState(false);
  const weekStart = startOfWeek(currentDate, { weekStartsOn: 1 });
  const days = Array.from({ length: 7 }, (_, i) => addDays(weekStart, i));

  const { data, isLoading } = useQuery({
    queryKey: ['planner-weekly', weekStart.toISOString()],
    queryFn: () => api.get(`/planner/weekly?date=${weekStart.toISOString()}`).then(r => r.data),
  });

  const regenerate = async () => {
    setRegenerating(true);
    try {
      const res = await api.post('/planner/regenerate');
      toast.success('Plan regenerated by AI!');
      qc.invalidateQueries({ queryKey: ['planner-weekly'] });
    } catch {
      toast.error('Regeneration failed — is the AI service running?');
    } finally {
      setRegenerating(false);
    }
  };

  return (
    <AppShell title="Weekly Planner">
      <div className="max-w-6xl mx-auto space-y-4">
        {/* Nav */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <button onClick={() => setCurrentDate(d => addDays(d, -7))} className="p-2 rounded-xl hover:bg-white/5 transition-colors">
              <ChevronLeft className="w-5 h-5" />
            </button>
            <span className="font-semibold">
              {format(weekStart, 'MMM d')} – {format(addDays(weekStart, 6), 'MMM d, yyyy')}
            </span>
            <button onClick={() => setCurrentDate(d => addDays(d, 7))} className="p-2 rounded-xl hover:bg-white/5 transition-colors">
              <ChevronRight className="w-5 h-5" />
            </button>
            <button onClick={() => setCurrentDate(new Date())} className="text-xs text-purple-400 hover:text-purple-300">Today</button>
          </div>
          <button
            onClick={regenerate}
            disabled={regenerating}
            className="flex items-center gap-2 text-sm btn-ghost"
          >
            {regenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <RefreshCw className="w-4 h-4" />}
            AI Regenerate
          </button>
        </div>

        {/* Calendar grid */}
        <div className="card overflow-hidden p-0">
          {/* Header */}
          <div className="grid grid-cols-8 border-b border-border">
            <div className="p-3 text-xs text-muted-foreground" />
            {days.map(d => {
              const isToday = format(d, 'yyyy-MM-dd') === format(new Date(), 'yyyy-MM-dd');
              return (
                <div key={d.toISOString()} className={`p-3 text-center border-l border-border ${isToday ? 'bg-purple-600/10' : ''}`}>
                  <p className="text-xs text-muted-foreground">{format(d, 'EEE')}</p>
                  <p className={`text-sm font-semibold mt-0.5 w-7 h-7 rounded-full flex items-center justify-center mx-auto ${isToday ? 'bg-purple-600 text-white' : ''}`}>
                    {format(d, 'd')}
                  </p>
                </div>
              );
            })}
          </div>

          {/* Time slots */}
          <div className="overflow-y-auto max-h-[60vh]">
            {HOURS.map(hour => (
              <div key={hour} className="grid grid-cols-8 border-b border-border/50 min-h-[60px]">
                <div className="p-2 text-xs text-muted-foreground text-right pr-3">{hour}:00</div>
                {days.map(d => {
                  const daySessions = data?.sessions?.filter((s: any) => {
                    const sessionDate = new Date(s.startTime);
                    return format(sessionDate, 'yyyy-MM-dd') === format(d, 'yyyy-MM-dd') &&
                           sessionDate.getHours() === hour;
                  }) || [];
                  return (
                    <div key={d.toISOString()} className="border-l border-border/50 p-1 relative">
                      {daySessions.map((s: any) => (
                        <div
                          key={s.id}
                          className="rounded-lg p-1.5 text-xs font-medium text-white truncate"
                          style={{ background: s.subject?.color || '#7C3AED' }}
                        >
                          {s.title}
                        </div>
                      ))}
                    </div>
                  );
                })}
              </div>
            ))}
          </div>
        </div>

        {data?.sessions?.length === 0 && !isLoading && (
          <div className="card text-center py-8 text-muted-foreground">
            <Clock className="w-10 h-10 mx-auto mb-2 opacity-50" />
            <p>No sessions scheduled this week</p>
            <button onClick={regenerate} className="btn-primary mt-4 text-sm flex items-center gap-2 mx-auto">
              <RefreshCw className="w-4 h-4" /> Generate with AI
            </button>
          </div>
        )}
      </div>
    </AppShell>
  );
}
